// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://junctwbyjtjhwjjioytc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1bmN0d2J5anRqaHdqamlveXRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxODY2MjQsImV4cCI6MjA3MDc2MjYyNH0.8atLoOXuQXwDUnFog-rhYBBdCK_Cp3vi6TZAyNdqtG0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});